# -*- coding: utf-8 -*-
"""news_producer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_U3PN5KVnDEjKSUtJ9mZKGiyJjgdop0
"""

from kafka import KafkaProducer
import json
from newsapi import NewsApiClient

# Kafka configuration
bootstrap_servers = 'localhost:9092'
producer_topic = 'my-news'

# Kafka producer initialization
producer = KafkaProducer(bootstrap_servers=bootstrap_servers,
                         value_serializer=lambda v: json.dumps(v).encode('utf-8'))

# NewsAPI configuration
news_api_key = "a8814d66653c46589a8fc8b31d0ba2aa"
newsapi = NewsApiClient(api_key=news_api_key)
sources = 'bbc-news,cnn,fox-news,nbc-news,the-guardian-uk,the-new-york-times,the-washington-post,usa-today,independent,daily-mail'

# Fetch news articles and send to Kafka
all_articles = newsapi.get_everything(q='france',
                                      sources=sources,
                                      language='en')

for article in all_articles['articles']:
    producer.send(producer_topic, value=article)
    print("Produced:", article['title'])

# Close the producer
producer.close()